### ISSUE TITLE
Roadmap дальнейшего развития Wine Launcher

### ISSUE THREAD

**Issue by hitman249** [hitman249/wine-launcher#2]
> Прелагайте свои варианты в комментариях

# Roadmap

- [x] При работе с патчами не хватает информации о статусе выполнения команд. Сейчас чтобы узнать выполнились ли команды и есть ли ошибки, нужно идти в логи. Не очень удобно. Идеально было бы видеть лог выполнения как в терминале (читай в режиме реального времени) или после завершения выполнения команд в окне программы
- [x] Поддержка установки из образов .iso, .nrg, .bin, .mdf и .img
- [x] Допилить страницу обновлений
- [x] Сделать анимированную превьюшку репозитория
